---
- name: Install elinks  httpd & wget
  hosts: serv1
  become: true
  tasks:
    - name: Install packages
      package:
        name: "{{item}}"
        state: present
      loop:
        - elinks
        - httpd
        - wget        
